class DeliveryRecord {
  String id,
      connoteNo,
      connoteDate,
      productCode,
      senderName,
      senderPhone,
      senderPostCode,
      recipientAccNo,
      recipientName,
      recipientAddr1,
      recipientAddr2,
      recipientPostCode,
      recipientCity,
      recipientState,
      recipientPhone,
      recipientEmail,
      weight,
      type,
      createdAt;

  DeliveryRecord(
      {required this.id,
      required this.connoteNo,
      required this.connoteDate,
      required this.productCode,
      required this.senderName,
      required this.senderPhone,
      required this.senderPostCode,
      required this.recipientAccNo,
      required this.recipientName,
      required this.recipientAddr1,
      required this.recipientAddr2,
      required this.recipientPostCode,
      required this.recipientCity,
      required this.recipientState,
      required this.recipientPhone,
      required this.recipientEmail,
      required this.weight,
      required this.type,
      required this.createdAt});

  factory DeliveryRecord.fromMap(Map<String, dynamic> map) {
    return DeliveryRecord(
        id                : map['id'] as String,
        connoteNo         : map['connote_no'] as String,
        connoteDate       : map['connote_date'] as String,
        productCode       : map['product_code'] as String,
        senderName        : map['sender_name'] as String,
        senderPhone       : map['sender_phone'] as String,
        senderPostCode    : map['sender_postcode'] as String,
        recipientAccNo    : map['recipient_acc_no'] as String,
        recipientName     : map['recipient_name'] as String,
        recipientAddr1    : map['recipient_addr1'] as String,
        recipientAddr2    : map['recipient_addr2'] as String,
        recipientPostCode : map['recipient_postcode'] as String,
        recipientCity     : map['recipient_city'] as String,
        recipientState    : map['recipient_state'] as String,
        recipientPhone    : map['recipient_phone'] as String,
        recipientEmail    : map['recipient_email'] as String,
        weight            : map['weight'] as String,
        type              : map['type'] as String,
        createdAt         : map['created_at'] as String);
  }
}
