class Product {
  String id,
      userId,
      pName,
      mainCate,
      subCate,
      brandMate,
      innerMate,
      stock,
      description,
      price,
      weight,
      maxQuan,
      photo1,
      photo2,
      photo3,
      photo4,
      photo5,
      rating,
      sold,
      isSale,
      isApproved,
      createdAt;

  Product(
      {required this.id,
      required this.userId,
      required this.pName,
      required this.mainCate,
      required this.subCate,
      required this.brandMate,
      required this.innerMate,
      required this.stock,
      required this.description,
      required this.price,
      required this.weight,
      required this.maxQuan,
      required this.photo1,
      required this.photo2,
      required this.photo3,
      required this.photo4,
      required this.photo5,
      required this.rating,
      required this.sold,
      required this.isSale,
      required this.isApproved,
      required this.createdAt});

  factory Product.fromMap(Map<String, dynamic> map) {
    return Product(
        id          : map['id'] as String,
        userId      : map['user_id'] as String,
        pName       : map['p_name'] as String,
        mainCate    : map['main_cate'] as String,
        subCate     : map['sub_cate'] as String,
        brandMate   : map['brand_mate'] as String,
        innerMate   : map['inner_mate'] as String,
        stock       : map['stock'] as String,
        description : map['description'] as String,
        price       : map['price'] as String,
        weight      : map['weight'] as String,
        maxQuan     : map['max_quan'] as String,
        photo1      : map['photo1'] as String,
        photo2      : map['photo2'] as String,
        photo3      : map['photo3'] as String,
        photo4      : map['photo4'] as String,
        photo5      : map['photo5'] as String,
        rating      : map['rating'] as String,
        sold        : map['sold'] as String,
        isSale      : map['is_sale'] as String,
        isApproved  : map['is_approved'] as String,
        createdAt   : map['created_at'] as String);
  }
}
